### ISSUE TITLE
Reserve usernames on forums for launch

### ISSUE THREAD

**Issue by leostera** [leostera/piclevel-api#12]
Register to any forum with the PicLevel username so that when we launch we already have them there.

Make sure to Hide You Ass and to use a @piclevel.com email address

**Comment by ignacio-developer** [comment]
foro-ptc.com

PicLevel : holahola22

forolockerz.com

PicLevel : holahola22

http://www.freewebhostingtalk.com/

PicLevel : holahola22

http://www.webhostingtalk.com/

PicLevel : holahola22

http://www.emoneyspace.com/

PicLevel : holahola22

http://www.talkgold.com/

PicLevel : holahola22
